# User.create(username: "Felix", password_digest: "Felix")
# Post.create(title: "Test", content: "testcontent", img: "imgURL", user_id: 1)
# Comment.create(text: "CommentFelix", post_id: 1, user_id: 1)
# Like.create(likeable: Post.first)
# Like.create(likeable: Comment.first)